# Generated by Django 3.2.2 on 2021-05-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_en', models.CharField(max_length=200)),
                ('country_jp', models.CharField(max_length=200)),
                ('zone_EMS', models.CharField(blank=True, max_length=3, null=True)),
                ('zone_International_Parcel_Post', models.IntegerField()),
                ('zone_Letter_Small_Packet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('zone', models.CharField(max_length=3)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EMS',
                'verbose_name_plural': 'EMS',
            },
        ),
        migrations.CreateModel(
            name='International_Parcel_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('zone', models.IntegerField()),
                ('airmail_price', models.IntegerField()),
                ('SAL_price', models.IntegerField()),
                ('surface_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'International Parcel Post',
                'verbose_name_plural': 'International Parcel Post',
            },
        ),
        migrations.CreateModel(
            name='Small_Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('zone', models.IntegerField()),
                ('airmail_price', models.IntegerField()),
                ('SAL_price', models.IntegerField()),
                ('surface_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Small Packet',
                'verbose_name_plural': 'Small Packet',
            },
        ),
    ]
