# Generated by Django 3.2.2 on 2021-05-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='international_parcel_post',
            name='SAL_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='international_parcel_post',
            name='airmail_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='international_parcel_post',
            name='surface_price',
            field=models.IntegerField(),
        ),
    ]
