# Generated by Django 3.2.2 on 2021-05-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_small_packet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Small_Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('zone', models.IntegerField()),
                ('airmail_price', models.IntegerField()),
                ('SAL_price', models.IntegerField()),
                ('surface_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Small Packet',
                'verbose_name_plural': 'Small Packet',
            },
        ),
    ]
