# Generated by Django 3.2.2 on 2021-05-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210513_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_en', models.CharField(max_length=200)),
                ('country_jp', models.CharField(max_length=200)),
                ('zone_EMS', models.IntegerField()),
                ('zone_International_Parcel_Post', models.IntegerField()),
                ('zone_Letter_Small_Packet', models.IntegerField()),
            ],
        ),
    ]
