# Generated by Django 3.2.2 on 2021-05-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_small_packet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='small_packet',
            name='SAL_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='small_packet',
            name='airmail_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='small_packet',
            name='surface_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
